// Single source of truth for every planet's identity and visuals — used by
// the detail view (Planet.jsx), the overview (SolarSystem.jsx), and the
// PlanetSelect dropdown, so all three always agree with each other.
export const PLANETS = [
  {
    id: 'mercury',
    name: 'Mercury',
    tagline: 'Swift & Scorched',
    texture: 'cratered',
    color: '#9c9c94',
    emissive: '#1a1a18',
    glow: '#c9c9c0',
    size: 0.7,
    hasRing: false,
    sunDistance: 3.2,
    orbitSpeed: 0.5,
    rotationSpeed: 0.5,
  },
  {
    id: 'venus',
    name: 'Venus',
    tagline: 'Veiled in Cloud',
    texture: 'clouds',
    color: '#e3c07f',
    emissive: '#3a2c10',
    glow: '#f5d999',
    size: 0.95,
    hasRing: false,
    sunDistance: 4.4,
    orbitSpeed: 0.42,
    rotationSpeed: 0.12,
  },
  {
    id: 'earth',
    name: 'Earth',
    tagline: 'The Blue Marble',
    texture: 'earth',
    color: '#2f6fdb',
    emissive: '#0a1a3a',
    glow: '#7dd3fc',
    size: 1,
    hasRing: false,
    sunDistance: 5.6,
    orbitSpeed: 0.36,
    rotationSpeed: 0.55,
  },
  {
    id: 'mars',
    name: 'Mars',
    tagline: 'The Red Frontier',
    texture: 'dusty',
    color: '#c1502e',
    emissive: '#2a0d05',
    glow: '#f2977a',
    size: 0.85,
    hasRing: false,
    sunDistance: 6.8,
    orbitSpeed: 0.3,
    rotationSpeed: 0.5,
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    tagline: 'King of Storms',
    texture: 'bands',
    color: '#d9a066',
    emissive: '#2c1c0c',
    glow: '#f0c896',
    size: 1.75,
    hasRing: false,
    sunDistance: 8.8,
    orbitSpeed: 0.18,
    rotationSpeed: 0.9,
  },
  {
    id: 'saturn',
    name: 'Saturn',
    tagline: 'The Ringed Jewel',
    texture: 'bands',
    color: '#e3c98f',
    emissive: '#2c260f',
    glow: '#f5e6b8',
    size: 1.55,
    hasRing: true,
    ringColor: '#c3b17e',
    sunDistance: 10.8,
    orbitSpeed: 0.14,
    rotationSpeed: 0.85,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    tagline: 'Tilted Ice Giant',
    texture: 'ice',
    color: '#9fd8e0',
    emissive: '#12262a',
    glow: '#cdeff5',
    size: 1.2,
    hasRing: true,
    ringColor: '#bfe9ee',
    sunDistance: 12.4,
    orbitSpeed: 0.1,
    rotationSpeed: 0.6,
  },
  {
    id: 'neptune',
    name: 'Neptune',
    tagline: 'Windswept Blue',
    texture: 'ice',
    color: '#4a6fe0',
    emissive: '#0c1533',
    glow: '#93aef7',
    size: 1.15,
    hasRing: false,
    sunDistance: 13.8,
    orbitSpeed: 0.08,
    rotationSpeed: 0.6,
  },
];

export const DEFAULT_PLANET = 'earth';

export function getPlanet(id) {
  return PLANETS.find((p) => p.id === id) || PLANETS.find((p) => p.id === DEFAULT_PLANET);
}
